### ISSUE TITLE
Update the Android Google Play badge

### ISSUE THREAD

**Issue by rocboronat** [Fewlaps/quitnow-website#10]
https://play.google.com/intl/en_us/badges/

**Comment by EsteveAguilera** [comment]
I've started to fix this issue on https://github.com/Fewlaps/quitnow-website/commit/daa8e91d7807555df58bea49efd2e0cc1009201a, but found another issue #13

**Comment by EsteveAguilera** [comment]
Closing the issue, it's already fixed in #16
