### ISSUE TITLE
The download section is shown before loading the whole webpage

### ISSUE THREAD

**Issue by rocboronat** [Fewlaps/quitnow-website#5]
Right now, when opening the website for first time, it shows the download section for a while. Later, when the whole website (or something like that) is loaded, the first section is shown.

It's not a big issue, with it's not as perfect as it should.

**Comment by nucliweb** [comment]
Hi @rocboronat 

I need the file [e:/www/LESS/style.less](https://github.com/Fewlaps/quitnow-website/blob/master/css/main.less#L1) for re-compile `main.less` with new styles.

Thanks

**Comment by rocboronat** [comment]
We just contacted with Pedro @ Xitrus, the author of the first version of the website. Let's expect this less file 🙌
